import React from "react";
import { useAppContext } from "../AppContext";
import ContactCard from "../components/ContactCard";
import ContactDetails from "../components/ContactDetails";
import InteractionLog from "../components/InteractionLog";
import InteractionForm from "../components/InteractionForm";
import { useContacts } from "../hooks/useContacts";

const ContactView = () => {
  const { setEditableContact, setMode, selectedContact, interactionMode, editableInteraction } =
    useAppContext();

  const { getContacts } = useContacts();

  const handleNewContactClick = () => {
    setEditableContact({
      _id: "", // should be generated by backend?
      firstName: "",
      lastName: "",
      email: "",
      phone: "",
      position: "",
      company: "",
      location: "",
      description: "",
    });
    setMode("create");
  };

  const contacts = getContacts;

  if (selectedContact) {
    return (
      <>
        {interactionMode === "view" && (
          <>
            <ContactDetails contact={selectedContact} />
            <InteractionLog contactId={selectedContact._id} />
          </>
        )}

        {interactionMode === "edit" || interactionMode === "create" ? (
          <InteractionForm
            interaction={editableInteraction || { _id: "", contactId: "", type: "", datetime: "", notes: "" }}
          />
        ) : null}
      </>
    );
  } else {
    return (
      <>
        {!contacts ? (
          <p>Loading contacts...</p>
        ) : (
          <>
            <div className="contacts-grid">
              {contacts?.map((contact) => (
                <ContactCard key={contact._id} contact={contact} />
              ))}
            </div>
            <button onClick={handleNewContactClick}>New Contact</button>
          </>
        )}
      </>
    );
  }
};

export default ContactView;
