// InteractionLog.tsx
import React from "react";
import { Interaction } from "../types";
import { useAppContext } from "../context/useAppContext";
import { useInteractions } from "../hooks/useInteractions";
import { Button, Card, CardHeader, CardBody, CardFooter, Textarea } from "@nextui-org/react";
import { EmailIcon, PhoneIcon, VideoCallIcon } from "../assets";

interface Props {
  contactId: string;
  onOpen: () => void;
}

const InteractionLog: React.FC<Props> = ({ contactId, onOpen }) => {
  const {
    selectedInteraction,
    selectedContact,
    setEditableInteraction,
    setInteractionMode,
    setSelectedInteraction,
  } = useAppContext();

  const { getInteractions } = useInteractions({ contactId });

  const handleNewInteractionClick = () => {
    setEditableInteraction({
      _id: "", // should be generated by backend
      contactId: selectedContact?._id ?? "",
      type: "",
      datetime: "",
      notes: "",
    });
    setSelectedInteraction(null);
    setInteractionMode("create");
    onOpen();
  };

  const handleInteractionEditClick = (interaction: Interaction) => {
    setSelectedInteraction(interaction);
    setEditableInteraction(selectedInteraction);
    setInteractionMode("edit");
    onOpen();
  };

  const interactions = getInteractions;

  if (!interactions) {
    return <div>Loading interactions...</div>;
  }

  return (
    <>
      {interactions.map((interaction) => (
        <Card>
          <React.Fragment key={interaction._id}>
            <CardHeader>
              <strong>
                <span style={{ display: "flex", alignItems: "center" }}>
                  {{
                    "phone call": <PhoneIcon />,
                    "video call": <VideoCallIcon />,
                    email: <EmailIcon />,
                  }[interaction.type] || "Unknown Type"}{" "}
                  &nbsp; {interaction.datetime.slice(0, 10)}
                </span>
              </strong>
            </CardHeader>
            <CardBody>
              <Textarea isReadOnly maxRows={100} variant="bordered" value={interaction.notes} />
            </CardBody>
            <CardFooter>
              <Button color="primary" onPress={() => handleInteractionEditClick(interaction)}>
                Edit
              </Button>
            </CardFooter>
          </React.Fragment>
        </Card>
      ))}
      <Button color="primary" onPress={handleNewInteractionClick}>
        Add Interaction
      </Button>
    </>
  );
};

export default InteractionLog;
