// InteractionLog.tsx
import React from "react";
import { Interaction } from "../types";
import { useAppContext } from "../context/useAppContext";
import { useInteractions } from "../hooks/useInteractions";
import { Button } from "@nextui-org/react";
import { EmailIcon, PhoneIcon, VideoCallIcon } from "../assets";

interface Props {
  contactId: string;
  onOpen: () => void;
}

const InteractionLog: React.FC<Props> = ({ contactId, onOpen }) => {
  const {
    selectedInteraction,
    selectedContact,
    setEditableInteraction,
    setInteractionMode,
    setSelectedInteraction,
  } = useAppContext();

  const { getInteractions } = useInteractions({ contactId });

  const handleNewInteractionClick = () => {
    setEditableInteraction({
      _id: "", // should be generated by backend
      contactId: selectedContact?._id ?? "",
      type: "",
      datetime: "",
      notes: "",
    });
    setSelectedInteraction(null);
    setInteractionMode("create");
    onOpen();
  };

  const handleInteractionEditClick = (interaction: Interaction) => {
    setSelectedInteraction(interaction);
    setEditableInteraction(selectedInteraction);
    setInteractionMode("edit");
    onOpen();
  };

  const interactions = getInteractions;

  if (!interactions) {
    return <div>Loading interactions...</div>;
  }

  return (
    <div className="interaction-log">
      <h3>Interactions</h3>
      <ul>
        {interactions.map((interaction) => (
          <React.Fragment key={interaction._id}>
            <li>
              <strong>
                <span style={{ display: "flex", alignItems: "center" }}>
                  Type: &nbsp;
                  {{
                    "phone call": <PhoneIcon />,
                    "video call": <VideoCallIcon />,
                    email: <EmailIcon />,
                  }[interaction.type] || "Unknown Type"}
                </span>
              </strong>
              <p>
                <strong>Date:</strong> {interaction.datetime.slice(0, 10)}
              </p>
              <p>
                <strong>Notes:</strong> {interaction.notes}
              </p>
            </li>
            <Button onPress={() => handleInteractionEditClick(interaction)}>Edit</Button>
          </React.Fragment>
        ))}
      </ul>
      <Button onPress={handleNewInteractionClick}>Add Interaction</Button>
    </div>
  );
};

export default InteractionLog;
